name: 'Chromatic Deployment'

on:
  push:
    branches:
      - main # main 브랜치로 푸시될 때 실행

jobs:
  chromatic:
    name: 'Run Chromatic'
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 4. Build Storybook
      - name: Build Storybook
        run: npm run build-storybook

      # 5. Run Chromatic
      - uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
